# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Venezuela Dreams' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #MobileClient
  pod 'AWSMobileClient', '~> 2.6.6'
  #Databases
  pod 'AWSDynamoDB', '~> 2.6.6'
  #User Login
  pod 'AWSUserPoolsSignIn', '~> 2.6.6'
  pod 'AWSAuthUI', '~> 2.6.6'
  #Analytics
  pod 'AWSPinpoint', '~> 2.6.6'

  # Pods for Venezuela Dreams

  target 'Venezuela DreamsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Venezuela DreamsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
